name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - master   # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18         # Vue CLI works best on Node 16–18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Add custom domain 
        run: echo "valerieremaker.com" > dist/CNAME


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
